theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "always"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 10

[editor.statusline]
left = [
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "spacer",
  "diagnostics",
  "register",
]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = [
  "file-encoding",
  "file-type",
  "separator",
  "primary-selection-length",
  "separator",
  "selections",
  "separator",
  "position",
  "separator",
  "spacer",
  "position-percentage",
  "total-line-numbers",
]


separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "┊"

[editor.lsp]
enable = true
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-s = ":w"
"A-w" = ":buffer-close"
C-p = "signature_help"

[keys.insert]
C-s = ":w"
C-p = "signature_help"

[keys.normal.space]
t = ":sh tree -a -L 3 --dirsfirst -I 'target|__pycache__|venv|.venv|.git'"
